wandb_version: 1

aug_prob:
  value: 0.5
batch_size:
  value: 4
csv:
  value: data.csv
encoder_model:
  value: resnet50
epochs:
  value: 200
learning_rate:
  value: 0.01
n_class:
  value: 1
optimizer:
  value: torch.optim.Adam
patch_size:
  value: (512, 512)
