csv:
  value: 'data.csv'
n_class:
  value: 1
batch_size:
  value: 16
epochs:
  value: 200
learning_rate:
  value: 1e-3
optimizer:
  value: torch.optim.Adam
encoder_model:
  value: 'resnet18'
patch_size:
  value: (512, 512)
aug_prob:
  value: 0.5