program: train.py
name: hyperparam_sweep
entity: glaseg
project: Gland_Seg
method: bayes
metric:
  name: Val_total_loss
  goal: minimize
parameters:
  csv:
    value: 'data.csv'
  n_class:
    value: 1
  batch_size:
    values: [4, 8, 16]
  epochs:
    value: 200
  learning_rate:
    values: [1e-2, 1e-3, 1e-4, 1e-5]
  optimizer:
    value: torch.optim.Adam
  encoder_model:
    values: ['resnet18', 'resnet34', 'resnet50']
  patch_size:
    value: (512, 512)
  aug_prob:
    value: 0.5